# Generated by Django 3.2 on 2022-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='incardshop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopcard',
        ),
        migrations.AddField(
            model_name='user',
            name='shopcard',
            field=models.ManyToManyField(related_name='users', to='api.Book'),
        ),
    ]
