# Generated by Django 3.2 on 2022-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220528_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cover',
            field=models.ImageField(upload_to='media/authors'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='media/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='media/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(upload_to='media/categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopcard',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.Book'),
        ),
    ]
