# Generated by Django 3.2 on 2022-06-08 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220608_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hits',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 12, 9, 48, 874307)),
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
